openapi: "3.0.2"
info:
  title: Shared OpenAPI Components
  version: "1.0"
servers: []
paths: {}

components:
  schemas:
    HomeLabBaseErrorModel:
      type: object
      required:
        - requestId
        - errorMessageParameters
        - errorMessageTranslationKey
        - extraInformation
      properties:
        requestId:
          type: string
        errorMessageTranslationKey:
          type: string
        errorMessageParameters:
          type: array
          items:
            type: string
          x-field-extra-annotation: "@lombok.Builder.Default"
        extraInformation:
          type: string
        stacktrace:
          type: string
  responses:
    400:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HomeLabBaseErrorModel"
    404:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HomeLabBaseErrorModel"
    409:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HomeLabBaseErrorModel"
    500:
      description: Generic Internal Server Error Response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HomeLabBaseErrorModel"
    502:
      description: Bad Gateway
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HomeLabBaseErrorModel"
